### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by TimTProd**
pastebin.py needs requests to work

### CODE REVIEW

**Comment by N0rz3** [comment]
Why ? The tool does not need requests

**Comment by TimTProd** [comment]
@N0rz3 well when I run the project in Docker Ubuntu container without requests library it throws an error: 
```
Traceback (most recent call last):
  File "/home/Zehef/zehef.py", line 3, in <module>
    import main; main.version()
  File "/home/Zehef/main.py", line 9, in version
    from lib import CLI
  File "/home/Zehef/lib/CLI.py", line 4, in <module>
    from output import main
  File "/home/Zehef/output/main.py", line 1, in <module>
    from modules import account, rep, breached, pastebin
  File "/home/Zehef/modules/pastebin.py", line 4, in <module>
    from ScrapeSearchEngine.SearchEngine import Google
  File "/usr/local/lib/python3.10/dist-packages/ScrapeSearchEngine/SearchEngine.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by N0rz3** [comment]
huh, it's weird yet I don't use `requests`?

**Comment by N0rz3** [comment]
and if ScrapeSearchEngine.SearchEngine needs requests and well normally when installing the module it must install it by itself

**Comment by N0rz3** [comment]
@TimTProd did you install scrape-search-engine?

**Comment by TimTProd** [comment]
Yes, installed, and have just re-runed the project on the host removing requests and scrape-search-engine, then installing requirements.txt. It still wants requests library

**Comment by N0rz3** [comment]
well I'm going to add it even if it's still weird but I'm not going to merge your commit I'm going to add it by hand

**Pull request closed without merging**
